// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>

int main(void)
{
    // Make 3 ints to allow for value swapping
    int f0 = 1;
    int f1 = 2;
    int buff = 0;

    // Make a sum to display, starting at 2 to include starting value of 2
    int sum = 2;

    // Make a loop where i iterates over fib numbers and is less than 4000000
    for (int i = 0; i < 4000000; i = f1)
    {
        // Store next fib number in buffer
        buff = f0 + f1;

        // Update previous fib number to current
        f0 = f1;

        // Update current to next
        f1 = buff;

        // if current is divisible by 2, add to sum
        if(f1 % 2 == 0)
        {
            sum = sum + f1;
        }
    }

    // Print sum
    printf("%i\n", sum);
}